import type { Metadata } from "next";
import { NaviMenu } from "@/components/NavigationMenu";
import { MenuBarNav } from "@/components/MenuBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            {/* <NaviMenu /> */}
            <MenuBarNav />
            <div>{children}</div>
        </section>
    );
}
