import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Manrope, Sarala } from "next/font/google";
import {
    CircleCheckBig,
    CircleX,
    InfoIcon,
    LoaderCircle,
    ShieldAlert,
} from "lucide-react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const manrope = Manrope({ subsets: ["latin"] });
const sarala = Sarala({
    subsets: ["latin"],
    weight: "400",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${sarala.className} antialiased`}>
                <main>{children}</main>
                <Toaster
                    toastOptions={{
                        // unstyled: true,
                        classNames: {
                            error: "text-red-400 font-bold",
                            success: "text-green-400 font-bold",
                            warning: "text-yellow-400 font-bold",
                            info: "text-blue-400 font-bold",
                        },
                    }}
                    richColors
                    position="top-right"
                />
            </body>
        </html>
    );
}
